### PR TITLE
fix(configure-db.php): fix that can't create PDO instance

### PR DESCRIPTION
**Pull request by oucb**

### CODE REVIEW

**Comment by HenryQW** [comment]
Hi @oucb, thanks for the PR. What issues does it address exactly? I'm having no issue running the latest via compose.

**Comment by oucb** [comment]
@HenryQW  can't create PDO instance for database connect without specify `dbname`, and can't refresh the content of `config.php`

**Comment by HenryQW** [comment]
What are the steps to reproduce the issues? I can’t seem to reproduce them.

If you are using docker run, make sure:

1. If the target postgres is a container too, it has to be in the same network as ttrss container.

2. If the target postgres is not a container, specify both DB_HOST and DB_PORT as environment variables.

**Comment by oucb** [comment]
Run Postgres:
```
docker run --name=pg-ttrss -d \
--net=ttrss --net-alias=pg \
-e POSTGRES_PASSWORD=ttrss \
-e POSTGRES_USER=root \
-e POSTGRES_DB=ttrss \
postgres
```
Run ttrss:
```
docker run --name=ttrss -d --restart=always \
    --net=ttrss -e SELF_URL_PATH="http://localhost:8081/" \
    -e DB_HOST=pg -e DB_PORT=5432 \
    -e DB_USER=root -e DB_PASS=ttrss -e DB_NAME=ttrss \
    -p 8081:80 ttrss
```

**Comment by HenryQW** [comment]
Hi, sorry for the late reply. Here is what I ran to get it work:
``` docker
docker network create ttrss

docker run -d --name=postgres --restart=always \
--net=ttrss --net-alias=pg \
-e PG_PASSWORD=mydbpass \
-e DB_EXTENSION=pg_trgm \
-p 5432:5432 \
sameersbn/postgresql:latest

docker run -dit --name=ttrss --restart=always \
--net=ttrss \
-e SELF_URL_PATH=http://localhost:181 \
-e DB_HOST=pg  \
-e DB_PORT=5432  \
-e DB_NAME=myttrss  \
-e DB_USER=postgres  \
-e DB_PASS=mydbpass  \
-p 181:80  \
wangqiru/ttrss
```

image

**Pull request closed without merging**
